- dd-java-agent/instrumentation/jax-rs-annotations/src/main/java/datadog/trace/instrumentation/jaxrs/JaxRsAnnotationsInstrumentation.java
- dd-java-agent/instrumentation/jax-rs-annotations/src/test/groovy/JaxRsAnnotationsInstrumentationTest.groovy
jax-rs is currently missing common OT tags for instrumented servers.  These changes add the span kind, http method, and url.
> Add tags to jax-rs spans

- dd-java-agent/instrumentation/jax-rs-annotations/src/main/java/datadog/trace/instrumentation/jaxrs/JaxRsAnnotationsInstrumentation.java
- dd-java-agent/instrumentation/jax-rs-annotations/src/main/java/datadog/trace/instrumentation/jaxrs/utils/ScopeStore.java
In cases where an exception is thrown in a JAX-RS controller, it can be advantageous not just marking the controller span as having errored.  These changes set the error tag for both controller and parent spans, but still log the exception object in the controller span.
Also includes a new `ScopeStore` class for marshaling scopes and whether they should be closed upon cleanup across byte buddy enter/exit methods to avoid prematurely closing spans not created by the instrumentation.
> Tag jax-rs parent spans upon error

- dd-java-agent/instrumentation/datastax-cassandra-2.3/datastax-cassandra-2.3.gradle
- dd-java-agent/instrumentation/jdbc/jdbc.gradle
- dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/AttributeKeys.java
- dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/ChannelFutureListenerInstrumentation.java
- dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/AttributeKeys.java
- dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/ChannelFutureListenerInstrumentation.java
Netty client tracing handler instrumentation is failing due to redundant attribute key value (should be client):
```
Caused by: java.lang.IllegalArgumentException: 'datadog.trace.instrumentation.netty40.server.HttpServerTracingHandler.span' is already in use
```
These changes correct this oversight and include necessary helper class injections.
Also pinning failing latest dependency test versions until they can be examined.
> Correct Netty client instrumentation

- dd-java-agent/instrumentation/instrumentation.gradle
Will allow shade/shadow users to build an agent with nonstandard Netty package path:
`./gradlew build -PrelocatedNettyPackage='my.shaded.package.path.netty'`
> Add Netty relocated package gradle property

- dd-java-agent/instrumentation/jax-rs-annotations/src/main/java/datadog/trace/instrumentation/jaxrs/JaxRsAnnotationsInstrumentation.java
- dd-java-agent/instrumentation/jax-rs-annotations/src/test/groovy/JaxRsAnnotationsInstrumentationTest.groovy
- dd-trace-api/src/main/java/com/signalfx/tracing/api/TraceSetting.java
- dd-trace-api/src/test/groovy/com/signalfx/tracing/TraceSettingTest.groovy
These changes introduce the `@TraceSetting` annotation for lower-level instrumentation configuration.  For the first provided feature, an `allowedExceptions` exception class array element will be used in determining whether to mark `jax-rs-controller` spans has having errored.
```
import com.signalfx.trace.api.TraceSetting;
@GET
@TraceSetting(allowedExceptions = {MyCustomException.class}
public void handle() throws MyCustomException {
// This JAX resource will not be marked with error tags
throw new MyCustomException();
}
```
> Add @TraceSetting and whitelist jax-rs-controller exceptions

- README.md
- dd-java-agent/instrumentation/jetty-8/src/main/java/datadog/trace/instrumentation/jetty8/HandlerInstrumentation.java
- dd-java-agent/instrumentation/jetty-8/src/test/groovy/JettyHandlerTest.groovy
- dd-java-agent/instrumentation/servlet-3/servlet-3.gradle
Updates the default enabled status for Jetty except for servlet 3 tests, which would need updating for effectively redundant spans.
> Enable Jetty server instrumentation by default

- dd-trace-ot/src/main/java/datadog/trace/common/writer/ZipkinV2Api.java
These changes address that we are only releasing connection resources on non-200 status codes for Zipkin trace submission:
URLConnection.java:
```
...
* Invoking the {@code close()} methods on the {@code InputStream} or {@code OutputStream} of an
* {@code URLConnection} after a request may free network resources associated with this
...
```
> Ensure Zipkin writers input stream closes

- dd-java-agent/instrumentation/jetty-8/src/main/java/datadog/trace/instrumentation/jetty8/JettyHandlerAdvice.java
- dd-java-agent/instrumentation/jetty-8/src/test/groovy/JettyHandlerTest.groovy
- dd-trace-ot/src/main/java/datadog/trace/common/writer/ZipkinV2Api.java
- dd-trace-ot/src/test/groovy/datadog/trace/api/writer/ZipkinV2ApiTest.groovy
Web servers currently have extremely limited operation names that cause undesired grouping of dissimilar traces.  These changes take advantage of the normalizing and 404 path-masking resource name decorators for http.url tag values and update the Zipkin span names to be more specific.
If some service owners are using non-standard paths that don't match [the mixed alphanumeric pattern](https://github.com/signalfx/signalfx-java-tracing/blob/master/dd-trace-ot/src/main/java/datadog/opentracing/decorators/URLAsResourceName.java#L15), replacing operation name in gateway could be necessary: https://docs.signalfx.com/en/latest/integrations/integrations-reference/integrations.signalfx.gateway.html#identify-and-replace-variables-in-span-names.
> Provide informative Zipkin span names for web servers

- gradle/dependencies.gradle
Resolves https://github.com/signalfx/signalfx-java-tracing/issues/28 to pull in JDK12-compatible Byte Buddy version.
> Update Byte Buddy dependency to 1.9.12

- dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
- dd-trace-ot/src/main/java/datadog/opentracing/propagation/B3HttpCodec.java
- dd-trace-ot/src/main/java/datadog/trace/common/sampling/AllSampler.java
Span propagation flags are determined during injection by the sampling priority of the root span.  Using the `AllSampler` bypasses the priority sampling mechanism such that it's always "unset".  These changes add the required initialization process to the tracer and setter in the sampler.  Resolves the issue of not providing the B3 sampled header and deferring to remote services' tracer implementation.
> Set span sampling priority in AllSampler

- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
- dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanBuilderTest.groovy
Adds a library and version tag to the global defaults for reporting tracer information.
> Include tracer version in global tags

- dd-trace-api/src/main/java/datadog/trace/api/interceptor/MutableSpan.java
- dd-trace-ot/src/main/java/datadog/opentracing/DDSpan.java
- dd-trace-ot/src/main/java/datadog/opentracing/DDSpanContext.java
- dd-trace-ot/src/main/java/datadog/trace/common/writer/ZipkinV2Api.java
- dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanTest.groovy
- dd-trace-ot/src/test/groovy/datadog/trace/api/writer/ZipkinV2ApiTest.groovy
Currently `span.log()` is a noop unless a map with the OT error object field is provided, in which case the object is expanded as a set of error tags.  These changes introduce a general log mechanism and restrict the cases where the expanded error tagging is applied.  Not keeping the existing error tagging process warrants updating all instrumentation tests and is out of scope for this functionality.
> Implement span.log()

- .circleci/config.yml
- dd-java-agent/instrumentation/http-url-connection/src/main/java/datadog/trace/instrumentation/http_url_connection/HttpUrlConnectionInstrumentation.java
- dd-java-agent/instrumentation/okhttp-3/src/main/java/datadog/trace/instrumentation/okhttp3/TracingInterceptor.java
- dd-trace-ot/src/main/java/datadog/trace/common/writer/ZipkinV2Api.java
Upstream feature additions have added undesired tracing of zipkin span reporting.  These changes filter out these requests and remove some cruft on my part.
> Don't trace Zipkin writer submissions

- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/decorator/HttpClientDecoratorTest.groovy
- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
µAPM considers 5xx errors, so we need to prevent clients from setting the error tag based on 4xx status codes by default.
> Modify default client error range

- dd-java-agent/instrumentation/java-concurrent/src/main/java/datadog/trace/instrumentation/java/concurrent/AbstractExecutorInstrumentation.java
- dd-java-agent/instrumentation/java-concurrent/src/test/groovy/ExecutorInstrumentationTest.groovy
Adds `CompletableFuture.ThreadPerTaskExecutor` to java.concurrent executor instrumentation whitelist in cases where `ForkJoinPool` isn't used for the internal `CompletableFuture` executor.
> Whitelist ThreadPerTaskExecutor

- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TagsAssert.groovy
- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
- dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanBuilderTest.groovy
- dd-trace-ot/src/test/groovy/datadog/opentracing/TraceInterceptorTest.groovy
- dd-trace-ot/src/test/groovy/datadog/trace/DDTracerTest.groovy
These tags aren't necessary or helpful for our traces.
> Remove default runtime.id and language tags

- dd-java-agent/instrumentation/elasticsearch/src/main/java/datadog/trace/instrumentation/elasticsearch/ElasticsearchTransportClientDecorator.java
- dd-java-agent/instrumentation/elasticsearch/transport-2/src/latestDepTest/groovy/Elasticsearch2NodeClientTest.groovy
- dd-java-agent/instrumentation/elasticsearch/transport-2/src/latestDepTest/groovy/Elasticsearch2TransportClientTest.groovy
- dd-java-agent/instrumentation/elasticsearch/transport-2/src/latestDepTest/groovy/springdata/Elasticsearch2SpringRepositoryTest.groovy
- dd-java-agent/instrumentation/elasticsearch/transport-2/src/latestDepTest/groovy/springdata/Elasticsearch2SpringTemplateTest.groovy
- dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/Elasticsearch2NodeClientTest.groovy
- dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/Elasticsearch2TransportClientTest.groovy
- dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/springdata/Elasticsearch2SpringRepositoryTest.groovy
- dd-java-agent/instrumentation/elasticsearch/transport-2/src/test/groovy/springdata/Elasticsearch2SpringTemplateTest.groovy
- dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/test/groovy/Elasticsearch53NodeClientTest.groovy
- dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/test/groovy/Elasticsearch53TransportClientTest.groovy
- dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/test/groovy/springdata/Elasticsearch53SpringRepositoryTest.groovy
- dd-java-agent/instrumentation/elasticsearch/transport-5.3/src/test/groovy/springdata/Elasticsearch53SpringTemplateTest.groovy
- dd-java-agent/instrumentation/elasticsearch/transport-5/src/test/groovy/Elasticsearch5NodeClientTest.groovy
- dd-java-agent/instrumentation/elasticsearch/transport-5/src/test/groovy/Elasticsearch5TransportClientTest.groovy
- dd-java-agent/instrumentation/elasticsearch/transport-6/src/test/groovy/Elasticsearch6NodeClientTest.groovy
- dd-java-agent/instrumentation/elasticsearch/transport-6/src/test/groovy/Elasticsearch6TransportClientTest.groovy
Provides more information than current `elasticsearch.query` as was initially done in v0.20.0 releases.
> Use ES action names for operations

- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- signalfx-java-tracing.gradle
* Align tag usage in database instrumentations with OpenTracing
* Add and document SIGNALFX_SPAN_TAGS configuration
* Add and document SIGNALFX_TRACING_ENABLED configuration
* Revert generalization of redis and elasticsearch operation names
* Add default ThreadPerTaskExecutor instrumentation for CompletableFuture
* Remove unnecessary/redundant tags
* Document compatibility with other JVM-based languages
> Version 0.28.0-sfx1

- README.md
- dd-java-agent/instrumentation/kafka-clients-0.11/kafka-clients-0.11.gradle
- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaProducerInstrumentation.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/TracingIterable.java
- dd-java-agent/instrumentation/kafka-clients-0.11/src/test/groovy/KafkaClientTest.groovy
- dd-java-agent/instrumentation/kafka-streams-0.11/kafka-streams-0.11.gradle
- dd-java-agent/instrumentation/kafka-streams-0.11/src/main/java/datadog/trace/instrumentation/kafka_streams/KafkaStreamsProcessorInstrumentation.java
- dd-java-agent/instrumentation/kafka-streams-0.11/src/test/groovy/KafkaStreamsTest.groovy
- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
In some environments [`maxUsableProduceMagic()`](https://github.com/signalfx/signalfx-java-tracing/blob/c02110a2a1d4847054f145ed2a2dbceb84844b19/dd-java-agent/instrumentation/kafka-clients-0.11/src/main/java/datadog/trace/instrumentation/kafka_clients/KafkaProducerInstrumentation.java#L78) may not have enough information to successfully disable context injection, causing undesired side effects for legacy record processing.
These changes add a `signalfx.instrumentation.kafka.attempt-propagation` property to disable injection and extraction attempts.
> Provide Kafka propagation toggle

- dd-trace-ot/src/main/java/datadog/opentracing/propagation/B3HttpCodec.java
- dd-trace-ot/src/test/groovy/datadog/opentracing/propagation/B3HttpExtractorTest.groovy
- dd-trace-ot/src/test/groovy/datadog/opentracing/propagation/B3HttpInjectorTest.groovy
Currently we drop the upper 64 bits for 128 bit trace ids, which is unnecessary and undesired.
> Add 128bit support to B3

- dd-java-agent/dd-java-agent.gradle
- gradle/publish-shadow.gradle
Changes recently pulled in shadow the bootstrap jar with the main agent, which places a new dependency on the shadow task for publishing: https://github.com/DataDog/dd-trace-java/commit/c275143eaefac1ac0670a0250fd82ecd0d1be7d2
These changes update the publishing extension for the agent's maven-publish usage to include the shadow component: https://imperceptiblethoughts.com/shadow/publishing/
> Ensure shadow jar is published

- dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceAdvice.java
- dd-java-agent/instrumentation/trace-annotation/src/test/groovy/ConfiguredTraceAnnotationsTest.groovy
- dd-java-agent/instrumentation/trace-annotation/src/test/groovy/TraceAnnotationsTest.groovy
- dd-java-agent/instrumentation/trace-annotation/src/test/groovy/TraceConfigTest.groovy
- dd-java-agent/testing/src/test/groovy/TraceCorrelationTest.groovy
- dd-trace-api/src/main/java/datadog/trace/api/CorrelationIdentifier.java
- dd-trace-api/src/main/java/datadog/trace/api/Ids.java
- dd-trace-api/src/test/groovy/datadog/trace/api/IdsTest.groovy
- dd-trace-ot/src/main/java/datadog/trace/common/writer/ZipkinV2Api.java
- gradle/java.gradle
These changes ensure that non-DD trace annotations use the same behavior as that of `com.signalfx.tracing.api.Trace` regarding operation names, and also ensure that logged MDC entries use hex representation for active span and its trace ids (resolves https://github.com/signalfx/signalfx-java-tracing/issues/68).  The latter required relocating the ids helper to the api project to prevent an unwanted dependency on the agent.
Also bumping up test timeout to reduce flake.
> Trace annotation and MDC usability improvements

- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/context/FieldBackedProvider.java
- dd-java-agent/instrumentation/hibernate/core-4.3/src/test/groovy/SpringJpaTest.groovy
- dd-java-agent/instrumentation/hibernate/src/main/java/datadog/trace/instrumentation/hibernate/HibernateDecorator.java
The latest hibernate-core release pulls in ByteBuddy 1.10.7, which obsoleted the noop transformer singleton: https://github.com/raphw/byte-buddy/commit/a88c34b0f16ffba99671afaeb2fe1f821fb7633d#diff-5c70b068f9fa1c336626a22ca79771d4L2157
These changes move its functionality into the `FieldBackedProvider` to avoid the loading failure:
```
java.lang.NoClassDefFoundError: net/bytebuddy/agent/builder/AgentBuilder$Transformer$NoOp
at datadog.trace.agent.tooling.context.FieldBackedProvider.additionalInstrumentation(FieldBackedProvider.java:359)
at datadog.trace.agent.tooling.Instrumenter$Default.instrument(Instrumenter.java:82)
at datadog.trace.agent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:151)
```
Also pulling in a null check added upstream and update tests for last …
> Account for removed NoOp Transformer and Hibernate changes

- dd-trace-api/src/main/java/datadog/trace/api/DDTags.java
- dd-trace-ot/src/main/java/datadog/trace/common/writer/ZipkinV2Api.java
- dd-trace-ot/src/test/groovy/datadog/trace/api/writer/ZipkinV2ApiTest.groovy
These changes ensure that the encoded zipkin span kind is uppercase to meet the v2 json specification.  Also add a 202 success check in the zipkin reporter.
> Adopt Zipkin kind enum

- README.md
- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
- dd-trace-ot/src/main/java/datadog/trace/common/writer/ZipkinV2Api.java
- dd-trace-ot/src/test/groovy/datadog/trace/api/writer/ZipkinV2ApiTest.groovy
These changes introduce the `recorded.value.max.length` config option to prevent Zipkin-encoded tag and log values from exceeding a specified size (default of 12288 chars).
> Add Zipkin recorded value max length config option

- README.md
Provides the relocated simple logger property for instrumentation logging.
> Add debug logging note in readme

- README.md
- dd-java-agent/instrumentation/jsp-2.3/jsp-2.3.gradle
- dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceAdvice.java
- dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceAnnotationUtils.java
- dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceAnnotationsInstrumentation.java
- dd-java-agent/instrumentation/trace-annotation/src/main/java/datadog/trace/instrumentation/trace_annotation/TraceConfigInstrumentation.java
- dd-java-agent/instrumentation/trace-annotation/src/test/groovy/TraceAnnotationsTest.groovy
- dd-java-agent/instrumentation/trace-annotation/src/test/java/dd/test/trace/annotation/SayTracedHello.java
- dd-java-agent/instrumentation/trace-annotation/trace-annotation.gradle
- dd-trace-api/src/main/java/datadog/trace/api/Config.java
These changes add a new configuration property `signalfx.trace.annotated.method.blacklist` that will turn the existing `TraceAdvice` methods into a noop.  This approach was taken to avoid the complexity of converting the `TraceAnnotationInstrumentation` to something like the current `TraceConfigInstrumentation`.  It will also ensure that (in)directly annotated methods will not be traced across instrumentation approaches.*
Also cherry picking restricting latest Tomcat test dependencies.
> Add Trace annotation blacklist configurable

- README.md
- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- dd-trace-ot/src/main/java/datadog/opentracing/PendingTrace.java
- dd-trace-ot/src/test/groovy/datadog/trace/DDTracerTest.groovy
This limits the writing of traces with more spans than the configured max.
Everything else about spans (propagation, id chains, etc.) still works;
only "at the last minute" do we drop the span before putting on the wire
to the upstream trace receiver.  2000 as the default was chosen somewhat
arbitrarily.
> Add maxSpansPerTrace config parameter, with a default of 2000.

- README.md
- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
- dd-trace-ot/src/main/java/datadog/opentracing/PendingTrace.java
- dd-trace-ot/src/test/groovy/datadog/trace/DDTracerTest.groovy
Set a default value of 0 (meaning "no limit"), add test ensuring that the default is in fact no limit.
> Make maxSpansPerTrace optional

- dd-java-agent/instrumentation/akka-http-10.0/src/test/groovy/AkkaHttpServerInstrumentationTest.groovy
- dd-java-agent/instrumentation/glassfish/src/test/groovy/GlassFishServerTest.groovy
- dd-java-agent/instrumentation/jax-rs-annotations-1/src/test/groovy/JaxRsAnnotationsInstrumentationTest.groovy
- dd-java-agent/instrumentation/jax-rs-annotations-2/src/test/groovy/DropwizardTest.groovy
- dd-java-agent/instrumentation/jax-rs-annotations-2/src/test/groovy/JaxRsAnnotationsInstrumentationTest.groovy
- dd-java-agent/instrumentation/jersey/src/test/groovy/JerseyInstrumentationTest.groovy
- dd-java-agent/instrumentation/jetty-8/src/test/groovy/JettyHandlerTest.groovy
- dd-java-agent/instrumentation/jsp-2.3/src/test/groovy/JSPInstrumentationBasicTests.groovy
- dd-java-agent/instrumentation/play-2.6/src/test/groovy/server/PlayServerTest.groovy
- dd-java-agent/instrumentation/servlet/request-2/src/test/groovy/JettyServlet2Test.groovy
- dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/AbstractServlet3Test.groovy
- dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/JettyServlet3Test.groovy
- dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/TomcatServlet3Test.groovy
- dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/SpringBootBasedTest.groovy
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TagsAssert.groovy
- dd-trace-api/src/main/java/datadog/trace/api/DDTags.java
- dd-trace-ot/src/main/java/datadog/opentracing/DDSpan.java
- Don't emit error.msg, error.type or error.stack tags
- Do emit sfx.error.{message, object, kind, stack} tags, with values appropriate to the OpenTracing semantic conventions at https://github.com/opentracing/specification/blob/master/semantic_conventions.md#log-fields-table
- Fix up tests accordingly
> ErrorAnalyzer: change names/values for error tags

- dd-java-agent/instrumentation/vertx/src/main/java/datadog/trace/instrumentation/vertx/VertxRxInstrumentation.java
- dd-java-agent/instrumentation/vertx/src/main/java8/datadog/trace/instrumentation/vertx/AsyncResultHandlerConsumerWrapper.java
- dd-java-agent/instrumentation/vertx/src/main/java8/datadog/trace/instrumentation/vertx/AsyncResultSingleAdvice.java
- dd-java-agent/instrumentation/vertx/src/rxHandlerTests/groovy/VertxRxServerTest.groovy
- dd-java-agent/instrumentation/vertx/src/rxHandlerTests/java/VertxRxWebTestServer.java
- dd-java-agent/instrumentation/vertx/vertx.gradle
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TraceAssert.groovy
- dd-java-agent/testing/src/test/groovy/AgentTestRunnerTest.groovy
Added instrumentation for AsyncResultSingle. This fixes the issue with reactive handlers causality.
> Support for Vert.x RxJava

- dd-trace-api/src/main/java/datadog/trace/api/Ids.java
- dd-trace-ot/src/main/java/datadog/trace/common/writer/Api.java
- dd-trace-ot/src/main/java/datadog/trace/common/writer/ZipkinV2Api.java
- dd-trace-ot/src/test/groovy/datadog/trace/api/writer/ZipkinV2ApiTest.groovy
A few quick localized wins in the performance (particularly in GC thrash) of writing to Zipkin format.
> Jackson streaming and ID performance tweaks

- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- signalfx-java-tracing.gradle
* Add max.spans.per.trace
* Breaking change: ErrorAnalyzer - adjust error.* names and values to sfx.* variants
* Add max.continuation.depth
* Add support for Vert.x RxJava
* Tweak performance of zipkin encoding
* Support @TraceSetting allowed exceptions in Spring webmvc.
* Normalize sql statements in db.statement
> Version 0.36.0-sfx5

- dd-trace-api/src/main/java/datadog/trace/api/Ids.java
- dd-trace-ot/src/main/java/datadog/trace/common/writer/Api.java
- dd-trace-ot/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
- dd-trace-ot/src/main/java/datadog/trace/common/writer/DDApi.java
- dd-trace-ot/src/main/java/datadog/trace/common/writer/ZipkinV2Api.java
* Use a short-circuit for turning 64-bit IDs into hex
* Remove some spurious extra allocations/doubled work
* Rework buffer strategy between serialization and writing to the wire to not double-copy traces.
> Significantly reduce thrash allocations in zipkin encoding

- dd-java-agent/instrumentation/vertx/src/main/java8/datadog/trace/instrumentation/vertx/VertxHandlerAdvice.java
- dd-java-agent/instrumentation/vertx/src/test/groovy/server/VertxServerTest.groovy
The current handler instrumentation assumes the event argument isn't null, which won't be the case for any `Handler<Void>` instances.
> Support vertx.runOnContext

- dd-trace-ot/src/main/java/datadog/trace/common/writer/ZipkinV2Api.java
Saw a customer where 7 GB of serialized traces were piled up in memory, blocked on one trace batch being written to our endpoint.  The endpoint apparently accepted the connection and the writes but had not responded with an HTTP status yet (ever); other traces were piled up in the queue waiting for this one to finish.  Adding a read timeout breaks the chain and at least allows the agent to not leak memory forever when this happens.
> Add a read timeout so that misbehaving endpoints don't cause a leak

- dd-java-agent/instrumentation/grizzly-2/grizzly-2.gradle
- dd-java-agent/instrumentation/jax-rs-client-1.1/jax-rs-client-1.1.gradle
- dd-java-agent/instrumentation/jax-rs-client-2.0/connection-error-handling-jersey/connection-error-handling-jersey.gradle
- dd-java-agent/instrumentation/jersey/jersey.gradle
A new release of jersey (3.0.0-M1 - added to maven repo yesterday) caused build fail. Two issues:
1. Grizzly tests failed because  Grizzly server doesn’t start with new version of jersey server
2. Muzzle validation fails because  https://repo1.maven.org/maven2/org/glassfish/jersey/core/jersey-server/maven-metadata.xml is missing 2.x versions.
> Jersey issue build fix

- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/decorator/ServerDecorator.java
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/decorator/BaseDecoratorTest.groovy
- dd-java-agent/agent-tooling/src/test/groovy/datadog/trace/agent/decorator/ServerDecoratorTest.groovy
- dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcStreamingTest.groovy
- dd-java-agent/instrumentation/grpc-1.5/src/test/groovy/GrpcTest.groovy
- dd-java-agent/instrumentation/play-2.4/src/test/groovy/server/PlayServerTest.groovy
- dd-java-agent/instrumentation/play-2.6/src/test/groovy/server/PlayServerTest.groovy
- dd-java-agent/instrumentation/ratpack-1.4/src/test/groovy/RatpackOtherTest.groovy
- dd-java-agent/instrumentation/ratpack-1.4/src/test/groovy/server/RatpackHttpServerTest.groovy
- dd-java-agent/instrumentation/spring-webflux-5/src/test/groovy/SpringWebfluxTest.groovy
- dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/SpringBootBasedTest.groovy
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TraceAssert.groovy
Only the local root span can have span.kind=server, because otherwise
it leads to undesired endpoint metrics in PG.
> Set span.kind=server only for receiving end of a distributed trace

- dd-trace-ot/src/main/java/datadog/trace/common/writer/ZipkinV2Api.java
- dd-trace-ot/src/test/groovy/datadog/trace/api/writer/ZipkinV2ApiTest.groovy
The current OTel collector will drop these root spans so it's better to avoid setting the unnecessary field.
> Don't set zipkin parentId on root spans

- dd-java-agent/instrumentation/vertx/src/main/java8/datadog/trace/instrumentation/vertx/VertxHandlerAdvice.java
- dd-java-agent/instrumentation/vertx/src/test/groovy/server/VertxServerTest.groovy
This was tested at the customer site and confirmed to fix their leak.
> Do not create spans/scopes for vertx timers when not in already in a trace context

- dd-trace-ot/src/main/java/datadog/trace/common/writer/DDAgentWriter.java
- dd-trace-ot/src/main/java/datadog/trace/common/writer/ZipkinV2Api.java
This is knowingly a short-term approach to this particular issue where the endpoint gets in a weird
state and traces pile up in memory.
Also set the connect timeout to 30s.
> Do endpoint I/O on the disruptor thread rather than another thread.

- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- signalfx-java-tracing.gradle
* Do endpoint I/O on the disruptor thread rather than another thread.
* Do not create spans/scopes for vertx timers when not in already in a trace context.
> Version 0.36.0-sfx8

- dd-java-agent/instrumentation/vertx/src/handlerTests/groovy/VertxServerTest.groovy
- dd-java-agent/instrumentation/vertx/src/test/groovy/server/VertxServerTest.groovy
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/asserts/TagsAssert.groovy
- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
These changes move the version information from default global tags to those of the local root.
> Only set tracing library tags on local root

- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- dd-trace-ot/dd-trace-ot.gradle
- dd-trace-ot/src/main/java/datadog/trace/common/writer/ZipkinV2Api.java
- dd-trace-ot/src/test/groovy/datadog/trace/api/writer/ZipkinV2ApiTest.groovy
These changes incorporate a configurable and enabled by default gzip encoder in the zipkin api.
> Add zipkin gzip encoding

- .circleci/config.yml
- dd-trace-ot/src/main/java/datadog/trace/common/writer/ZipkinV2Api.java
- dd-trace-ot/src/test/groovy/datadog/trace/api/writer/ZipkinV2ApiTest.groovy
Ensures the intended behavior of https://github.com/signalfx/signalfx-java-tracing/commit/ecbe03ade3a2dc2de2da144d335868d838123b63 functionality persists through span encoding.
Also removes java 9 and 10 CI test runs since the test image no longer sets their respective `JAVA_x_HOME`.
> Don't derive Zipkin server kind from span type

- dd-trace-ot/src/main/java/datadog/opentracing/decorators/URLAsResourceName.java
- dd-trace-ot/src/test/groovy/datadog/opentracing/decorators/URLAsResourceNameTest.groovy
Potential fix for SWAT-1618: too high cardinality operation names when they contain email addresses.
> Normalize away path segments that contain "@"

- dd-java-agent/agent-bootstrap/src/main/java/datadog/trace/bootstrap/instrumentation/TraceParentHeaderFormatter.java
- dd-java-agent/instrumentation/grizzly-2/src/main/java/datadog/trace/instrumentation/grizzly/GrizzlyHttpHandlerInstrumentation.java
- dd-java-agent/instrumentation/grizzly-2/src/test/groovy/GrizzlyTest.groovy
- dd-java-agent/instrumentation/jetty-6/src/main/java/datadog/trace/instrumentation/jetty6/JettyHandlerAdvice.java
- dd-java-agent/instrumentation/jetty-6/src/test/groovy/JettyHandlerTest.groovy
- dd-java-agent/instrumentation/jetty-8/src/main/java/datadog/trace/instrumentation/jetty8/JettyHandlerAdvice.java
- dd-java-agent/instrumentation/jetty-8/src/test/groovy/JettyHandlerTest.groovy
- dd-java-agent/instrumentation/netty-3.8/src/main/java/datadog/trace/instrumentation/netty38/server/HttpServerResponseTracingHandler.java
- dd-java-agent/instrumentation/netty-3.8/src/test/groovy/Netty38ServerTest.groovy
- dd-java-agent/instrumentation/netty-4.0/src/main/java/datadog/trace/instrumentation/netty40/server/HttpServerResponseTracingHandler.java
- dd-java-agent/instrumentation/netty-4.0/src/test/groovy/Netty40ServerTest.groovy
- dd-java-agent/instrumentation/netty-4.1/src/main/java/datadog/trace/instrumentation/netty41/server/HttpServerResponseTracingHandler.java
- dd-java-agent/instrumentation/netty-4.1/src/test/groovy/Netty41ServerTest.groovy
- dd-java-agent/instrumentation/servlet/request-2/src/main/java/datadog/trace/instrumentation/servlet2/Servlet2Advice.java
- dd-java-agent/instrumentation/servlet/request-2/src/test/groovy/JettyServlet2Test.groovy
- dd-java-agent/instrumentation/servlet/request-3/src/main/java/datadog/trace/instrumentation/servlet3/Servlet3Advice.java
- dd-java-agent/instrumentation/servlet/request-3/src/test/groovy/AbstractServlet3Test.groovy
- dd-trace-api/src/main/java/datadog/trace/api/Config.java
Optionally pass trace context in http response via Server-Timing.
If SIGNALFX_SERVER_TIMING_CONTEXT is turned on, pass trace context
in traceparent form over a Server-Timing header.
https://www.w3.org/TR/server-timing/
https://www.w3.org/TR/trace-context/#traceparent-header
> Optionally pass trace context in http response via Server-Timing.

- dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/HandlerAdapterInstrumentation.java
- dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/HandlerMappingInstrumentation.java
- dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/AppConfig.groovy
- dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/SpringBootBasedTest.groovy
- dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/TestController.groovy
This works around the issue in SWAT-1755 ticket, where span name was not updated if some `HandlerInterceptor` throws an exception from `preHandle`
> Add a separate HandlerMappingInstrumentation to update server span name when the corresponding handler got selected

- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- signalfx-java-tracing.gradle
- Optionally pass trace context in http response via Server-Timing
- Add a separate HandlerMappingInstrumentation to update server span name when the corresponding handler got selected
> Version 0.48.0-sfx1

- dd-java-agent/instrumentation/mongo/driver-3.1/src/main/java/datadog/trace/instrumentation/mongo/MongoClientInstrumentation.java
- dd-java-agent/instrumentation/mongo/driver-3.1/src/test/groovy/MongoClientTest.groovy
- dd-java-agent/instrumentation/mongo/driver-async-3.3/src/main/java/datadog/trace/instrumentation/mongo/MongoAsyncClientInstrumentation.java
- dd-java-agent/instrumentation/mongo/driver-async-3.3/src/test/groovy/MongoAsyncClientTest.groovy
Fixes #122: Mongo instrumentation may duplicate traced command spans
Check for already injected TracingCommandListener before injecting.
Patch derived from the fix for a similar issue in open-telemetry/opentelemetry-java-instrumentation.
> Avoid doubly tracing MongoClientSettingsBuilder

- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- signalfx-java-tracing.gradle
- Camel instrumentation
- Avoid doubly tracing MongoClientSettingsBuilder
> Version 0.48.0-sfx2

- gradle/dependencies.gradle
Mitigates CVE-2019-14893, CVE-2020-25649, and possibly others
> upgrade jackson-databind to latest.

- dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
- dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java
...and mitigate transitive jackson vulns.
Noting this as spicy, since [quite a few changes were made in jmxfetch](https://github.com/DataDog/jmxfetch/blob/master/CHANGELOG.md) since `0.35.0`.
Upstream lost a number of dependencies, including `jackson-databind` and `commons-io` (and several others).  As a result, we have to now depend on `commons-io` directly (for IOUtils).
> 🌶️  Update to latest jmxfetch upstream 🌶️

- README.md
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/log/LogContextScopeListener.java
- dd-java-agent/instrumentation/commons-httpclient-2/commons-httpclient-2.gradle
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/log/injection/LogContextInjectionTestBase.groovy
- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- dd-trace-api/src/main/java/datadog/trace/api/CorrelationIdentifier.java
- dd-trace-api/src/main/java/datadog/trace/api/GlobalTracer.java
- dd-trace-api/src/main/java/datadog/trace/api/Tracer.java
- dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
- dd-trace-ot/src/main/java/datadog/opentracing/DDTracer.java
* New system property / env var: `SIGNALFX_ENVIRONMENT_NAME`. `default: ""`.
* If environment name is set, it is added to span tags as `environment`
* Expose both service name and environment to loggers similar to how trace and span IDs are exposed
> Expose service name and environment via MDC

- dd-java-agent/agent-jmxfetch/src/main/java/datadog/trace/agent/jmxfetch/JMXFetch.java
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/log/LogContextScopeListener.java
- dd-trace-ot/dd-trace-ot.gradle
- dd-trace-ot/src/main/java/datadog/trace/common/writer/ddagent/DDAgentApi.java
- dd-trace-ot/src/main/java/datadog/trace/common/writer/ddagent/SafeRequestBuilder.java
- dd-trace-ot/src/test/groovy/datadog/trace/common/writer/ddagent/SafeRequestBuilderTest.groovy
Context 1: https://github.com/square/okhttp/issues/6738#issuecomment-1190949487
Context 2: https://github.com/DataDog/dd-trace-java/pull/3682
This code was forked from the upstream dd repo, so this fix includes the core of the `SafeRequestBuilder` fix in [#3682](https://github.com/DataDog/dd-trace-java/pull/3682).
This applies to api requests that pass through the `DDAgentApi` class. It does not address requests originating in the `RecordingUploader` class (unsupported by Splunk) and it does not address requests originating in user application code.
> Omit header values from okhttp exception messages.
