signalfx/signalfx-java-tracing

- gradle/publish.gradle
Also getting maven publishing credentials working.
> Change name of maven artifacts to include 'signalfx'

- dd-java-agent/instrumentation/jax-rs-client/connection-error-handling-jersey/src/main/java/datadog/trace/instrumentation/connection_error/jersey/JerseyClientConnectionErrorInstrumentation.java
- dd-java-agent/instrumentation/jax-rs-client/connection-error-handling-resteasy/src/main/java/datadog/trace/instrumentation/connection_error/resteasy/ResteasyClientConnectionErrorInstrumentation.java
- dd-java-agent/instrumentation/jax-rs-client/src/test/groovy/JaxRsClientTest.groovy
Since 3xx and 4xx status codes aren't considered to warrant error tags in traced clients, jax-rs exceptions thrown upon these responses should be ignored in instrumentation.  These changes whitelist `javax.ws.rs.core.Response`'s `RedirectionException` and `ClientErrorException`.
> Don't set error tag for 3xx or 4xx jax-rs client errors

- README.md
Documents supported versions of added instrumentation.
> Add spring data to readme

- README.md
- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
- dd-trace-ot/src/test/groovy/datadog/opentracing/DDSpanBuilderTest.groovy
Updates the span tags property/env var info and adds configuration information to readme.
> Update and document span tags configuration

- README.md
- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- dd-trace-api/src/test/groovy/datadog/trace/api/ConfigTest.groovy
Allows usage of `SIGNALFX_TRACING_ENABLED` env var.
> Update tracing property name

- dd-java-agent/instrumentation/jedis-1.4/src/main/java/datadog/trace/instrumentation/jedis/JedisClientDecorator.java
- dd-java-agent/instrumentation/jedis-1.4/src/main/java/datadog/trace/instrumentation/jedis/JedisInstrumentation.java
- dd-java-agent/instrumentation/jedis-1.4/src/test/groovy/JedisClientTest.groovy
- dd-java-agent/instrumentation/lettuce-5/src/main/java8/datadog/trace/instrumentation/lettuce/LettuceClientDecorator.java
- dd-java-agent/instrumentation/lettuce-5/src/test/groovy/LettuceAsyncClientTest.groovy
- dd-java-agent/instrumentation/lettuce-5/src/test/groovy/LettuceReactiveClientTest.groovy
- dd-java-agent/instrumentation/lettuce-5/src/test/groovy/LettuceSyncClientTest.groovy
Provides more informative operation names for redis instrumentation.
> Use redis command as operation name

- README.md
And fix wrapping, not all paragraphs were correctly wrapped in the Markdown source.
> Update README with note about other JVM-based languages

- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- signalfx-java-tracing.gradle
* Conform to OT tags for database and message broker instrumentations
* Stabilize db.instance values over connection statuses
> Version 0.28.0-sfx2

- README.md
* Also update version support for Jedis and Vertx
> Document support of Hibernate in README

- .circleci/config.yml
- dd-java-agent/instrumentation/aws-java-sdk-1.11.0/aws-java-sdk-1.11.0.gradle
- dd-java-agent/instrumentation/java-concurrent/src/test/groovy/ExecutorInstrumentationTest.groovy
- dd-java-agent/instrumentation/jersey/jersey.gradle
- dd-java-agent/instrumentation/jetty-6/jetty-6.gradle
- dd-java-agent/instrumentation/spring-data/spring-data.gradle
Updates tests and circle config to pass.
> Circle updates

- README.md
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/decorator/BaseDecorator.java
- dd-java-agent/instrumentation/jax-rs-annotations-1/src/main/java/datadog/trace/instrumentation/jaxrs1/JaxRsAnnotationsInstrumentation.java
- dd-java-agent/instrumentation/jax-rs-annotations-2/src/main/java/datadog/trace/instrumentation/jaxrs2/JaxRsAnnotationsInstrumentation.java
- dd-java-agent/instrumentation/spring-webmvc-3.1/src/main/java/datadog/trace/instrumentation/springweb/HandlerAdapterInstrumentation.java
- dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/SpringBootBasedTest.groovy
- dd-java-agent/instrumentation/spring-webmvc-3.1/src/test/groovy/test/TestController.groovy
- dd-java-agent/testing/src/main/groovy/datadog/trace/agent/test/base/HttpServerTest.groovy
Add support for @TraceSetting(allowedExceptions) for SpringMVC + refactoring in JAXRS to reuse a logic.
> Spring webmvc allowed exceptions support

- dd-java-agent/instrumentation/java-concurrent/src/slickTest/groovy/SlickTest.groovy
- dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/ConnectionInstrumentation.java
- dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCDecorator.java
- dd-java-agent/instrumentation/jdbc/src/main/java/datadog/trace/instrumentation/jdbc/JDBCUtils.java
- dd-java-agent/instrumentation/jdbc/src/test/groovy/JDBCInstrumentationTest.groovy
- dd-java-agent/instrumentation/jdbc/src/test/groovy/SqlNormalizerTest.groovy
Regex-based approach to normalizing sql string and numeric literals away (replacing them, per industry standard, with "?").
> Normalize sql

- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- signalfx-java-tracing.gradle
* Reduce thrash allocations in Zipkin encoding
* Support vertx.runOnContext
> Version 0.36.0-sfx6

- dd-java-agent/instrumentation/jax-rs-client-1.1/jax-rs-client-1.1.gradle
- dd-java-agent/instrumentation/jax-rs-client-2.0/connection-error-handling-jersey/connection-error-handling-jersey.gradle
- dd-java-agent/instrumentation/jersey/jersey.gradle
This reverts commit fe577212874f08e132b5429714f03d1730d243c6
> Revert "Disable muzzle check for jersey-client and jersey-server"

- .circleci/config.yml
- README.md
- buildSrc/src/main/groovy/MuzzlePlugin.groovy
- dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/Cleaner.java
- dd-java-agent/instrumentation/apache-httpclient-4/apache-httpclient-4.gradle
- dd-java-agent/instrumentation/jax-rs-client-1.1/jax-rs-client-1.1.gradle
- dd-java-agent/instrumentation/ratpack-1.4/ratpack-1.4.gradle
- dd-java-agent/instrumentation/servlet/servlet.gradle
- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- gradle/java.gradle
- signalfx-java-tracing.gradle
These changes pull in muzzle plugin updates and limit supported versions of ratpack.  Also preparing updated version commit.
> Version 0.36.0-sfx7 and muzzle fixes

- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- signalfx-java-tracing.gradle
* Add zipkin gzip encoding.
* Only set tracing library tags on local root.
> Version 0.36.0-sfx9

- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- signalfx-java-tracing.gradle
* Normalize away path segments that contain "@"
> Version 0.36.0-sfx11

- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- signalfx-java-tracing.gradle
- Include upstream 0.48.0 additions
> Version 0.48.0-sfx0

- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- signalfx-java-tracing.gradle
- Mark deprecation of this library
- Update snakeyaml version
> 0.48.0-sfx3

- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- signalfx-java-tracing.gradle
> Version 0.48.0-sfx4

- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- signalfx-java-tracing.gradle
- Update jackson in transitive dependency
> Version 0.48.0-sfx5

- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- signalfx-java-tracing.gradle
- Expose service name and environment via MDC
> Version 0.48.0-sfx6

- dd-java-agent/agent-profiling/profiling-uploader/profiling-uploader.gradle
- dd-java-agent/instrumentation/finatra-2.9/finatra-2.9.gradle
- dd-java-agent/instrumentation/log4j2/log4j2.gradle
- dd-smoke-tests/profiling-integration-tests/profiling-integration-tests.gradle
- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- dd-trace-ot/dd-trace-ot.gradle
- gradle/dependencies.gradle
- gradle/java.gradle
- signalfx-java-tracing.gradle
Updates log4j to 2.17.2 and jackson-databind to 2.13.2.1
> Security update for release

- dd-java-agent/agent-jmxfetch/agent-jmxfetch.gradle
- dd-java-agent/instrumentation/glassfish/glassfish.gradle
Please refer to the issue `Requesting updated jar with commons-io and snakeyaml latest versions
` https://github.com/signalfx/signalfx-java-tracing/issues/146 for more details
> Fix commons-io and snakeyaml vulnerabilities

- dd-trace-api/src/main/java/datadog/trace/api/Config.java
- signalfx-java-tracing.gradle
I failed to update the version number in code for sfx9 so we will need to push to sfx10 now.
> Update versions for sfx10
